# ==============================================================================
# VEHICLE CONFIGURATION
# Settings for Veins/SUMO vehicles
# ==============================================================================

[General]
# ==============================================================================
# VEINS MANAGER
# ==============================================================================
*.manager.updateInterval = 0.2s # Can be overridden in simulation_scenario.ini files

# ==============================================================================
# VEHICLE MOBILITY
# ==============================================================================
*.node[*].mobility.typename = "VeinsInetMobility"
*.node[*].mobility.initFromDisplayString = false

# ==============================================================================
# VEHICLE RADIO - PHYSICAL LAYER (Layer 1: PHY)
# ==============================================================================
*.node[*].numWlanInterfaces = 1

# Radio Medium
*.node[*].wlan[0].radio.radioMediumModule = "radioMediumSV[0]"

# Frequency & Bandwidth
# ==============================================================================
# Global center frequency: center frequency is set in the transmitter and receiver modules
*.node[*].wlan[0].radio.centerFrequency = 10.825GHz

# Global bandwidth: bandwidth is set in the transmitter and receiver modules
*.node[*].wlan[0].radio.bandwidth = 250MHz

# Global Bitrate for all others components: setted to transmitter bitrate
*.node[*].wlan[0].bitrate = 20Mbps 
# ==============================================================================
# Transmitter
*.node[*].wlan[0].radio.transmitter.centerFrequency = 10.825GHz # Not needed, but for clarity (same as global)
*.node[*].wlan[0].radio.transmitter.bandwidth = 250MHz # Not needed, but for clarity (same as global)
*.node[*].wlan[0].radio.transmitter.bitrate = 20Mbps # Override Global Bitrate in UPLINK (VEC -> SAT) for ASYMMETRIC UPLINK/DOWNLINK
*.node[*].wlan[0].radio.transmitter.power = 10W 
*.node[*].wlan[0].radio.transmitter.preambleDuration = 1us
*.node[*].wlan[0].radio.transmitter.headerLength = 8B
*.node[*].wlan[0].radio.transmitter.modulation = "QAM-16"

# Receiver
*.node[*].wlan[0].radio.receiver.centerFrequency = 10.825GHz # Not needed, but for clarity (same as global)
*.node[*].wlan[0].radio.receiver.bandwidth = 250MHz # Not needed, but for clarity (same as global)
*.node[*].wlan[0].radio.receiver.bitrate = 150Mbps # Override Global Bitrate in DOWNLINK (SAT -> VEC) for ASYMMETRIC UPLINK/DOWNLINK
*.node[*].wlan[0].radio.receiver.snirThreshold = 4dB
*.node[*].wlan[0].radio.receiver.sensitivity = -85dBm
*.node[*].wlan[0].radio.receiver.energyDetection = -85dBm
*.node[*].wlan[0].radio.receiver.modulation = "QAM-16"
# ==============================================================================

# Antenna Type (ConstantGainAntenna: fixed gain) + Mobility Module
*.node[*].wlan[0].radio.antenna.typename = "ConstantGainAntenna"
*.node[*].wlan[0].radio.antenna.mobilityModule = "^.^.^.mobility"
*.node[*].wlan[0].radio.antenna.gain = 28dB # 34dB

# Antenna Mobility (AttachedMobility: antenna moves with the node) + Mobility Module
*.node[*].wlan[0].radio.antenna.mobility.typename = "AttachedMobility"
*.node[*].wlan[0].radio.antenna.mobility.mobilityModule = "^.^.^.^.mobility"
*.node[*].wlan[0].radio.antenna.mobility.offsetX = 0m
*.node[*].wlan[0].radio.antenna.mobility.offsetY = 0m
*.node[*].wlan[0].radio.antenna.mobility.offsetZ = 1.5m
*.node[*].wlan[0].radio.antenna.mobility.initialElevation = 90deg

# ==============================================================================
# VEHICLE MAC LAYER (Layer 2)
# ==============================================================================
*.node[*].wlan[0].mac.fullDuplex = true
*.node[*].wlan[0].mac.useAck = false
*.node[*].wlan[0].mac.mtu = 32000B
*.node[*].wlan[0].mac.queue.packetCapacity = -1

# ==============================================================================
# VISUALIZATION
# ==============================================================================
*.node[*].wlan[0].radio.displayCommunicationRange = true
