# ==============================================================================
# CELLULAR NETWORK CONFIGURATION
# 5G Settings
# ==============================================================================
# Number of Resource Blocks (RB) in a Single Cell
# **.numBands = 50
# ==============================================================================
# GNODEB (BASE STATION) CONFIGURATION
# ==============================================================================
*.gNB.mobility.initFromDisplayString = false
*.gNB.mobility.initialX = 300m
*.gNB.mobility.initialY = 300m
*.gNB*.gateway = "upf" # "upfTN"

# gNodeB Cell Configuration (Single Cell Scenario)
*.gNB.macNodeId = 1
*.gNB.macCellId = 1

# gNodeB Network Interface (D2D Capability)
*.gNB.cellularNic.d2dCapable = true

# gNodeB Dual Connectivity (EN-DC) 
*.gNB.cellularNic.dualConnectivityEnabled = true


# ==============================================================================
# Background Traffic Configuration
# ==============================================================================
# # Carrier Aggregation Configuration (Optional)
# *.carrierAggregation.numComponentCarriers = 1
# *.carrierAggregation.componentCarrier[0].carrierFrequency = 2GHz
# *.carrierAggregation.componentCarrier[0].numBands = 6         
# *.carrierAggregation.componentCarrier[0].numerologyIndex = 0   # μ=0 -> 15kHz SCS

# # Connect the gNodeB to the Component Carrier
# *.gNB.cellularNic.numCarriers = 1
# *.gNB.cellularNic.channelModel[0].componentCarrierModule = "carrierAggregation.componentCarrier[0]"

# # Connect the UEs to the Component Carrier
# *.node[*].cellularNic.numNRCarriers = 1
# *.node[*].cellularNic.nrChannelModel[0].componentCarrierModule = "carrierAggregation.componentCarrier[0]"

# Enable background traffic generator
# *.gNodeB.numBgCells = 10
# *.bgCell[*].bgScheduler.isNr = true
# *.bgCell[*].bgScheduler.txPower = 23

# # Position of the background gNodeB
# *.bgCell[*].mobility.initialX = 500m
# *.bgCell[*].mobility.initialY = 500m

# # Number and position of background UEs in the background cells
# *.bgCell[*].bgTrafficGenerator.numBgUes = 100000000
# *.bgCell[*].bgTrafficGenerator.bgUE[*].mobility.initialX = uniform(300m,400m)
# *.bgCell[*].bgTrafficGenerator.bgUE[*].mobility.initialY = uniform(300m,400m)

# # Background traffic in the background cells
# *.bgCell[*].bgTrafficGenerator.bgUE[*].generator.typename = "TrafficGeneratorCbr"
# *.bgCell[*].bgTrafficGenerator.bgUE[*].generator.startTimeDl = uniform(5s,5.05s)
# *.bgCell[*].bgTrafficGenerator.bgUE[*].generator.packetSizeDl = 150B
# *.bgCell[*].bgTrafficGenerator.bgUE[*].generator.periodDl = 0.0001s

# ==============================================================================
# UPF (USER PLANE FUNCTION) CONFIGURATION
# ==============================================================================
# Packet Filtering
*.upf.pwgFilterMode = "ALL" # Filter mode: ALL, TCP, UDP
*.upfNTN.pwgFilterMode = "ALL" # Filter mode: ALL, TCP, UDP