# ==============================================================================
# OMNET++ MAIN CONFIGURATION FILE
# HybridSCSV5GFusion Simulation
# ==============================================================================
# 
# This is the main configuration file that includes all modular configuration
# files and defines the simulation scenarios.
#
# File Structure:
#
#
# ==============================================================================

# ==============================================================================
# INCLUDE CONFIGURATIONS 
# ==============================================================================

include config_general.ini
# include config_napoli.ini

include config_nonterrestrial.ini
include config_terrestrial.ini
include config_car.ini


# ==============================================================================
# INCLUDE CONFIGURATIONS STRATEGIES 
# ==============================================================================
include config_strategies/config_cellular_only.ini
include config_strategies/config_satellite_only.ini

include config_strategies/config_hybrid_time.ini
include config_strategies/config_hybrid_coverage.ini
include config_strategies/config_hybrid_qos.ini

include config_strategies/config_energy_aware.ini


# ==============================================================================
# INCLUDE STATISTICS CONFIGURATION 
# ==============================================================================
#! include config_stats.ini
