# ==============================================================================
# OMNET++ MAIN CONFIGURATION FILE
# HybridSCSV5GFusion Simulation
# ==============================================================================
# 
# This is the main configuration file that includes all modular configuration
# files and defines the simulation scenarios.
#
# File Structure:
# - 1. configs/config_general.ini:   - General Simulation Settings, Output, Debugging and Position Converter and Coordinate Systems
#
# - 2. configs/config_5G.ini:        - 5G Network Configuration and Parameters
#
# - 3. config_satellite.ini:         - Network Topology and Node Counts and Complete Satellite Configuration
#
# - 4. config_v2s.ini:               - Vehicle/Node Configuration for V2S Communication
#
# - 5. config_strategies/:           - Individual Strategy Configurations 
# 
# - 6. config_stats.ini:            - Statistics and Recording Configuration
#
# ==============================================================================

# ==============================================================================
# INCLUDE COMMON CONFIGURATIONS {1-4}
# ==============================================================================
include config_general.ini
# include config_5G.ini
include config_satellite.ini
include config_v2s.ini

# ==============================================================================
# INCLUDE CONFIGURATIONS STRATEGIES {5}
# ==============================================================================
include config_strategies/config_cellular_only.ini
include config_strategies/config_satellite_only.ini
include config_strategies/config_hybrid_time.ini
include config_strategies/config_hybrid_coverage.ini
include config_strategies/config_hybrid_energy.ini

# ==============================================================================
# INCLUDE STATISTICS CONFIGURATION {6}
# ==============================================================================
# include config_stats.ini
