# ==============================================================================
# OMNET++ MAIN CONFIGURATION FILE
# HybridSCSV5GFusion Simulation using 4G and Satellite Networks
# ==============================================================================

# ==============================================================================
# INCLUDE CONFIGURATIONS 
# ==============================================================================
include config_general.ini
# ==============================================================================
# NETWORK DEFINITION
network = HybridFusionNet4G
# ==============================================================================
include config_nonterrestrial.ini
# ==============================================================================
include config_terrestrial4G.ini
# ==============================================================================
include config_car.ini
# ==============================================================================

# ==============================================================================
# INCLUDE CONFIGURATIONS STRATEGIES 
# ==============================================================================
include config_strategies/config_cellular_only.ini
include config_strategies/config_satellite_only.ini
include config_strategies/config_hybrid_time.ini
include config_strategies/config_hybrid_coverage.ini
include config_strategies/config_hybrid_qos.ini
include config_strategies/config_energy_aware.ini
