# ==============================================================================
# OMNET++ MAIN CONFIGURATION FILE
# HybridSCSV5GFusion Simulation
# ==============================================================================
# 
# This is the main configuration file that includes all modular configuration
# files and defines the simulation scenarios.
#
# File Structure:
# - 1. configs/config_general.ini:      - General Simulation Settings, Output, Debugging and Position Converter and Coordinate Systems
#
# - 2. configs/config_cellular5G.ini:   - 5G Network Configuration and Parameters
#
# - 3. configs/config_vcellular5G.ini:  - Vehicle/Node Configuration for 5G Communication
#
# - 4. config_satellite.ini:            - Network Topology and Node Counts and Complete Satellite Configuration
#
# - 5. config_v2satellite.ini:          - Vehicle/Node Configuration for V2S Communication
#
# - 6. config_strategies/:              - Individual Strategy Configurations 
 
# - 7. config_stats.ini:                - Statistics and Recording Configuration
#
# ==============================================================================

# ==============================================================================
# INCLUDE COMMON CONFIGURATIONS {1,2,3,4,5}
# ==============================================================================
include config_general.ini
include config_cellular5G.ini
include config_vcellular5G.ini
include config_satellite.ini
include config_v2satellite.ini

# ==============================================================================
# INCLUDE CONFIGURATIONS STRATEGIES {6}
# ==============================================================================
include config_strategies/config_cellular_only.ini
include config_strategies/config_satellite_only.ini
include config_strategies/config_hybrid_time.ini
include config_strategies/config_hybrid_coverage.ini
include config_strategies/config_hybrid_energy.ini

# ==============================================================================
# INCLUDE STATISTICS CONFIGURATION {7}
# ==============================================================================
#! include config_stats.ini
