# ==============================================================================
# Configuration: SATELLITE ONLY
# HybridCar using only satellite network (Cellular disabled)
# ==============================================================================
[Config SatelliteOnlyBaseline]
description = "HybridCar: Satellite Only - Baseline (Don't run this)"

# ==============================================================================
# INTERFACE CONFIGURATION
# ==============================================================================
# Enable satellite, disable cellular
*.node[*].numWlanInterfaces = 1
*.node[*].hasCellular = false # Disable cellular, use only satellite
*.node[*].ipv4.configurator.interfaces = "wlan0"

# Disable HybridInterfaceManager
*.node[*].enableSwitching = false

# ==============================================================================
# NETWORK CONFIGURATOR
# ==============================================================================
*.configurator.config = xmldoc("../config_networks/netconfig_satellite.xml")
*.configurator.updateInterval = 1s

# Dump for debugging
# *.configurator.dumpTopology = true
# *.configurator.dumpConfig = "dumps/dump_sat.xml"

# ==============================================================================
# UPDATE INTERVALS
# ==============================================================================
*.manager.updateInterval = 0.2s                # Veins Manager
*.satellite[*].mobility.updateInterval = 1s    # Satellite (satellites move fast)
*.MCC[*].mobility.updateInterval = 200s        # MCC (static ground stations)
**.updateInterval = 0.1s                       # General mobility update


# ==============================================================================
# SatelliteOnlyWithTraffic (UDP Echo + UDP Basic)
# ==============================================================================
[Config SatelliteOnlyWithTraffic]
extends = SatelliteOnlyBaseline
description = "HybridCar: Satellite Only with Traffic"

include config_app.ini

# **.channel.display-string = "ls=,0"
# **.display-string = "p=10000,1000"
# **.node[*].display-string = "i=device/car;is=vs"


# # ==============================================================================
# # SCENARIO CONFIGURATION
# # ==============================================================================
[Config SatelliteOnlyAlert]
extends = SatelliteOnlyBaseline
description = "HybridCar: Satellite Only with Traffic"

*.node[*].wlan[0].queue.packetCapacity = -1
*.satellite[*].cnl[0].queue.packetCapacity = -1
*.satellite[*].cnl[1..2].queue.packetCapacity = -1
*.MCC[*].wlan[*].queue.packetCapacity = -1

sim-time-limit = 30s
# Server listen on port 5000 for alerts
*.server.numApps = 1
*.server.app[0].typename = "AlertServerApp"
*.server.app[0].localPort = 5000
*.server.app[0].destPort = 5001
*.server.app[0].messageLength = 200B
*.server.app[0].sendInterval = 100ms

# Assume node[0] is the one that triggers the alert (the "incident vehicle")
*.node[0].numApps = 1
*.node[0].app[0].typename = "UdpBasicApp"
*.node[0].app[0].destAddresses = "server"
*.node[0].app[0].destPort = 5000
*.node[0].app[0].localPort = 5001
*.node[0].app[0].messageLength = 200B
*.node[0].app[0].packetName = "AlertTriggerPacket"
*.node[0].app[0].startTime = 5s
*.node[0].app[0].sendInterval = 100ms
# *.node[0].app[0].stopTime = 11s 

# The other nodes (node[1] to node[99]) are pure listeners for the alert on port 5001
*.node[1..99].numApps = 1
*.node[1..99].app[0].typename = "UdpBasicApp"
*.node[1..99].app[0].localPort = 5001
*.node[1..99].app[0].destAddresses = "" 
*.node[1..99].app[0].destPort = 0
*.node[1..99].app[0].sendInterval = 1s   
*.node[1..99].app[0].messageLength = 200B


# ==============================================================================
# SatelliteOnlyWithTraffic (UDP Echo + UDP Basic)
# ==============================================================================
# [Config SatelliteOnlyWithTraffic100ms]
# extends = SatelliteOnlyBaseline
# description = "HybridCar: Satellite Only with Traffic"
# include config_app.ini
# *.node[*].app[0].sendInterval = exponential(500ms)
# *.node[*].app[0].startTime = 5s + ancestorIndex(0) * 2s
# *.node[*].app[1].startTime = 3s + ancestorIndex(0) * 2s
# ==============================================================================
# SatelliteOnlyWithTraffic (UDP Echo + UDP Basic)
# ==============================================================================
# [Config SatelliteOnlyWithTraffic50ms]
# extends = SatelliteOnlyBaseline
# description = "HybridCar: Satellite Only with Traffic"
# include config_app.ini
# *.node[*].app[0].sendInterval = exponential(50ms)
# # ==============================================================================
# # SatelliteOnlyWithTraffic (UDP Echo + UDP Basic)
# # ==============================================================================
# [Config SatelliteOnlyWithTraffic50ms]
# extends = SatelliteOnlyBaseline
# description = "HybridCar: Satellite Only with Traffic"
# include config_app.ini
# *.node[*].app[0].sendInterval = exponential(50ms)
# # ==============================================================================
# # SatelliteOnlyWithTraffic (UDP Echo + UDP Basic)
# # ==============================================================================
# [Config SatelliteOnlyWithTrafficAndIgnoreAllInterference]
# extends = SatelliteOnlyBaseline
# description = "HybridCar: Satellite Only with Traffic"
# include config_app.ini
# **.analogModel.ignoreAllInterference = true
# # ==============================================================================
# # SatelliteOnlyWithTraffic (UDP Echo + UDP Basic)
# # ==============================================================================
# [Config SatelliteOnlyWithTrafficAndSnirThreshold]
# extends = SatelliteOnlyBaseline
# description = "HybridCar: Satellite Only with Traffic"
# include config_app.ini
# *.satellite[*].cnl[1..2].radio.receiver.snirThreshold = -200dB
# # ==============================================================================
# # SatelliteOnlyWithTraffic (UDP Echo + UDP Basic)
# # ==============================================================================
# [Config SatelliteOnlyWithTrafficAndErrorModel]
# extends = SatelliteOnlyBaseline
# description = "HybridCar: Satellite Only with Traffic"
# include config_app.ini
# *.satellite[*].cnl[1..2].radio.receiver.errorModel.typename = ""
# *.satellite[*].cnl[1..2].radio.receiver.snirThreshold = -200dB
# # ==============================================================================
# # SatelliteOnlyWithTraffic (UDP Echo + UDP Basic)
# # ==============================================================================
# [Config SatelliteOnlyWithUnlimitedQueue]
# extends = SatelliteOnlyWithTraffic
# *.MCC[*].wlan[*].queue.packetCapacity = -1 
# *.node[*].wlan[0].queue.packetCapacity = -1
# *.satellite[*].cnl[1..2].queue.packetCapacity = -1  
# # ==============================================================================
# # SatelliteOnlyWithTraffic (UDP Echo + UDP Basic)
# # ==============================================================================
# [Config SatelliteOnlyWithUnlimitedQueueWithAck]
# extends = SatelliteOnlyWithUnlimitedQueue
# *.node[*].wlan[0].mac.useAck = true       
# *.node[*].wlan[0].mac.retryLimit = 7      
# *.satellite[*].cnl[1..2].mac.useAck = true
# *.satellite[*].cnl[1..2].mac.retryLimit = 7