# ==============================================================================
# Configuration: CELLULAR ONLY
# HybridCar using only cellular network (Satellite disabled)
# ==============================================================================

[Config CellularOnlyBaseline]
description = "HybridCar: Cellular Only - Baseline (Don't run this)"

# ==============================================================================
# INTERFACE CONFIGURATION
# ==============================================================================
# Enable cellular, disable satellite
*.node[*].hasCellular = true
*.node[*].numWlanInterfaces = 0 # Disable satellite interface
*.node[*].ipv4.configurator.interfaces = "cellular"

# Disable HybridInterfaceManager
*.node[*].enableSwitching = false

# ==============================================================================
# NETWORK CONFIGURATOR
# ==============================================================================
*.configurator.config = xmldoc("../config_networks/netconfig_cellular.xml")
*.configurator.updateInterval = 1s

# Dump for debugging
# *.configurator.dumpTopology = true
# *.configurator.dumpConfig = "dumps/dump_cellular.xml"

# ==============================================================================
# UPDATE INTERVALS
# ==============================================================================
*.manager.updateInterval = 0.2s                # Veins Manager
*.satellite[*].mobility.updateInterval = 1s    # Satellite mobility update
*.MCC[*].mobility.updateInterval = 200s        # MCC mobility update
**.updateInterval = 0.1s                       # General mobility update

# ==============================================================================
# CellularOnlyWithTraffic (UDP Echo + UDP Basic)
# ==============================================================================
[Config CellularOnlyWithTraffic]
extends = CellularOnlyBaseline
description = "HybridCar: Cellular Only with Traffic"

include config_app.ini




# # ==============================================================================
# # SCENARIO CONFIGURATION
# # ==============================================================================
[Config CellularOnlyAlert]
extends = CellularOnlyBaseline
description = "HybridCar: Cellular Only with Traffic"

*.node[*].wlan[0].queue.packetCapacity = -1
*.satellite[*].cnl[0].queue.packetCapacity = -1
*.satellite[*].cnl[1..2].queue.packetCapacity = -1
*.MCC[*].wlan[*].queue.packetCapacity = -1

sim-time-limit = 30s
# Server listen on port 5000 for alerts
*.server.numApps = 1
*.server.app[0].typename = "AlertServerApp"
*.server.app[0].localPort = 5000
*.server.app[0].destPort = 5001
*.server.app[0].messageLength = 200B
*.server.app[0].sendInterval = 100ms

# Assume node[0] is the one that triggers the alert (the "incident vehicle")
*.node[0].numApps = 1
*.node[0].app[0].typename = "UdpBasicApp"
*.node[0].app[0].destAddresses = "server"
*.node[0].app[0].destPort = 5000
*.node[0].app[0].localPort = 5001
*.node[0].app[0].messageLength = 200B
*.node[0].app[0].packetName = "AlertTriggerPacket"
*.node[0].app[0].startTime = 5s
*.node[0].app[0].sendInterval = 100ms
# *.node[0].app[0].stopTime = 11s 

# The other nodes (node[1] to node[99]) are pure listeners for the alert on port 5001
*.node[1..99].numApps = 1
*.node[1..99].app[0].typename = "UdpBasicApp"
*.node[1..99].app[0].localPort = 5001
*.node[1..99].app[0].destAddresses = "" 
*.node[1..99].app[0].destPort = 0
*.node[1..99].app[0].sendInterval = 1s   
*.node[1..99].app[0].messageLength = 200B
